name: PlayerInfoScoreBoard
main: space\yurisi\PlayerInfoScoreBoard
version: 2.0
depend:
  - SecureCoinAPI
api: 4.0.0
author: yurisi
website: homepage.yurisi.space
description: プレイヤーの情報をスコアボードにて表示します。
